[package]
name = "disk-segmentation-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "disk-segmentation-app"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2" }

[dependencies]
tauri = { version = "2" }
serde = { version = "1", features = ["derive"] }
scanner-core = { path = "../../engine/crates/scanner-core" }
sysinfo = "0.32"

[profile.release]
panic = "abort"
